# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=20)),
            ],
        ),
    ]
